


```{r knitr-opts, echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, echo = FALSE, warning = FALSE)
```


```{r, get-studies-to-use}
library(Rlabkey)
library(data.table)
geMetaData <- labkey.selectRows(
                        baseUrl = "https://www.immunespace.org",
                        folderPath = "/Studies/",
                        schemaName = "assay.ExpressionMatrix.matrix",
                        queryName = "inputSamples_computed",
                        colNameOpt = "rname")
keepCols <- c("biosample_participantid",
              "biosample_study_time_collected",
              "run_dataoutputs_name")
geMetaData <- geMetaData[ , colnames(geMetaData) %in% keepCols ]

geMetaData$study <- paste0("SDY", sapply(strsplit(geMetaData$biosample_participantid, "\\."), "[", 2))
geMetaData$expression_matrix <- gsub("\\.tsv", "", geMetaData$run_dataoutputs_name)

geMetaData <- geMetaData[ geMetaData$biosample_study_time_collected >= 0, ]
geMetaData <- data.table(geMetaData)

geMetaData <- geMetaData[ , hasData := 0 %in% unique(biosample_study_time_collected) &
                                       length(unique(biosample_study_time_collected)) > 1,
                            by = .(biosample_participantid)]
geMetaData <- geMetaData[ hasData == TRUE ]
```

```{r, retrieve-data-loop-alternative}
library(ImmuneSpaceR)
library(Biobase)
esets <- lapply(unique(geMetaData$study), function(study){
    con <- CreateConnection(study)
    eset <- con$getGEMatrix(con$cache$GE_matrices$name)
})

# Combine esets
eset <- ImmuneSpaceR:::.combineEMs(esets)
```

```{r, separate-expression-data}
# subset eset by pids in geMetaData$hasData
pidsWithData <- unique(geMetaData$biosample_participantid)
eset <- eset[ , eset$participant_id %in% pidsWithData ]

# for each pid in pData generate
pd <- pData(eset)
em <- exprs(eset)
pids <- unique(pd$participant_id)

tmp <- data.frame(matrix(nrow = nrow(em), ncol = length(pids)))
rownames(tmp) <- rownames(em)
colnames(tmp) <- pids

for(pid in pids){
    baseline <- eset[ , eset$participant_id == pid & eset$study_time_collected == 0 ]
    baselineEm <- exprs(baseline)
    post <- eset[ , eset$participant_id == pid & eset$study_time_collected != 0 ]
    postEm <- exprs(post)
    maxEm <- apply(postEm, 1, max)
    tmp[, match(pid, colnames(tmp))] <- maxEm - baselineEm
}

fc <- data.table(tmp, keep.rownames = TRUE)
```

```{r, create-pdata}
keepCols <- c("participant_id", "exposure_process_preferred")
pd <- pd[, colnames(pd) %in% keepCols]
pd <- pd[ !duplicated(pd), ]

# Demographics
demographics <- labkey.selectRows(
    baseUrl = "https://www.immunespace.org",
    folderPath = "/Studies/",
    schemaName = "study",
    queryName = "demographics",
    colNameOpt = "rname"
)
keepCols <- c("participantid", "gender", "age_reported", "ethnicity", "race")
demographics <- demographics[ , colnames(demographics) %in% keepCols]
pd <- merge(pd, demographics, by.x = "participant_id", by.y = "participantid")

# Condition
studyInfo <- labkey.selectRows(
    baseUrl = "https://www.immunespace.org",
    folderPath = "/Studies/",
    schemaName = "immport",
    queryName = "study",
    colNameOpt = "rname"
)

study <- sapply(strsplit(pd$participant_id, "\\."), "[", 2)
pd$study <- paste0("SDY", study)

pd$condition <- studyInfo$condition_studied[ match(pd$study, studyInfo$study_accession)]

pd$newCondition <- sapply(pd$condition, function(x) {
    if( grepl("healthy|normal|naive", x, ignore.case = TRUE)){
        return("Healthy")
    }else if(grepl("influenza|H1N1", x, ignore.case = TRUE)){
        return("Influenza")
    }else if(grepl("CMV", x, ignore.case = TRUE)){
        return("CMV")
    }else if(grepl("TB|tuberculosis", x, ignore.case = TRUE)){
        return("Tuberculosis")
    }else if(grepl("Yellow Fever", x, ignore.case = TRUE)){
        return("Yellow_Fever")
    }else if(grepl("Mening", x, ignore.case = TRUE)){
        return("Meningitis")
    }else if(grepl("Malaria", x, ignore.case = TRUE)){
        return("Malaria")
    }else if(grepl("HIV", x, ignore.case = TRUE)){
        return("HIV")
    }else if(grepl("Dengue", x, ignore.case = TRUE)){
        return("Dengue")
    }else if(grepl("ZEBOV", x, ignore.case = TRUE)){
        return("Ebola")
    }else if(grepl("Hepatitis", x, ignore.case = TRUE)){
        return("Hepatitis")
    }else if(grepl("Smallpox|vaccinia", x, ignore.case = TRUE)){
        return("Smallpox")
    }else if(grepl("JDM|Dermatomyositis", x, ignore.case = TRUE)){
        return("Dermatomyositis")
    }else if(grepl("West Nile", x, ignore.case = TRUE)){
        return("West_Nile")
    }else if(grepl("Zika", x, ignore.case = TRUE)){
        return("Zika")
    }else if(grepl("Varicella", x, ignore.case = TRUE)){
        return("Varicella_Zoster")
    }else{
        return("Unknown")
    }
})

pd$ageGroup <- sapply(pd$age_reported, function(x){
    if(x < 10){
        return("< 10")
    }else if(x >= 10 & x < 20){
        return("10 to 20")
    }else if(x >= 20 & x < 30){
        return("20 to 30")
    }else if(x >= 30 & x < 40){
        return("30 to 40")
    }else if(x >= 40 & x < 50){
        return("40 to 50")
    }else if(x >= 50 & x < 60){
        return("50 to 60")
    }else if(x >= 60 & x < 70){
        return("60 to 70")
    }else if(x >= 70){
        return("> 70")
    }else{
        return("Unknown")
    }
})

pdata <- pd
```


```{r, shared-summary-variables}
groupingVar <- "newCondition"
btms <- UpdateAnno::emory_blood_transcript_modules
```


```{r, summarize-data-for-grouped-box-plot}
# Genes first
genesDT <- melt(fc,
                id.vars = c("rn"),
                measure.vars = grep("rn",
                                      colnames(fc),
                                      value = TRUE,
                                      invert = TRUE)
                  )
setnames(genesDT, c("variable", "rn"), c("participantId","gbValue"))

# BTMs
summarizeBTM <- function(geneDFsubset){
    res <- unname(sapply(names(btms), function(nm){
      d <- mean(geneDFsubset[ gbValue %in% btms[[nm]], value ])
    }))
}

btmsDT <- genesDT[ , list(value = summarizeBTM(.SD),
                          gbValue = names(btms)),
                     by = "participantId"]

# Add back grouping variables to facilitate plotting
addPlottingColumns <- function(dt){
    dt[, Condition := pdata$newCondition[match(dt$participantId, pdata$participant_id)] ]
    dt[, Study := gsub("^SUB\\d+\\.", "SDY", dt$participantId) ]
}

genesDT <- addPlottingColumns(genesDT)
btmsDT <- addPlottingColumns(btmsDT)

boxPlotData <- list(Gene = genesDT, Btm = btmsDT)
```


```{r, save-output}
outputPath <- "~/R/ImmuneSpaceGeneFinder/data/"
saveRDS(boxPlotData, file = paste0(outputPath, "new_boxplot_data.rds"))
```

